site_name: Nexus Platform Documentation
site_description: The Ultimate Plugin-Based Application Platform
site_author: Nexus Team
site_url: https://dnviti.github.io/Nexus/

repo_name: dnviti/nexus-platform
repo_url: https://github.com/dnviti/nexus-platform
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/README.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - First Plugin: getting-started/first-plugin.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - Core Components: architecture/core-components.md
      - Event System: architecture/events.md
      - Security: architecture/security.md
  - Plugin Development:
      - Overview: plugins/README.md
      - Basics: plugins/basics.md
      - API Routes: plugins/api-routes.md
      - Database: plugins/database.md
      - Testing: plugins/testing.md
      - Advanced: plugins/advanced.md
      - Events: plugins/events.md
      - Services: plugins/services.md
  - API Reference:
      - Overview: api/README.md
      - Core Classes: api/core.md
      - Authentication: api/auth.md
      - Events: api/events.md
      - Plugins: api/plugins.md
      - Admin: api/admin.md
      - Users: api/users.md
  - Deployment:
      - Overview: deployment/README.md
      - Docker: deployment/docker.md
      - Kubernetes: deployment/kubernetes.md
      - Monitoring: deployment/monitoring.md
      - Development: deployment/development.md
      - Bare Metal: deployment/bare-metal.md
      - Cloud: deployment/cloud.md
  - Guides:
      - Overview: guides/README.md
      - Configuration: guides/configuration.md
      - Development: guides/development.md
      - Plugins: guides/plugins.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs

copyright: Copyright &copy; 2024 Nexus Team
