name: Feature Request
description: Suggest an idea or enhancement for Nexus
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

        Please search existing issues and discussions first to avoid duplicates.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - Core Framework Enhancement
        - New Plugin
        - CLI Tool Improvement
        - Documentation Enhancement
        - Developer Experience
        - Performance Improvement
        - API Enhancement
        - Security Feature
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: "Alternatively, we could..."
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used and who would benefit from it.
      placeholder: |
        - As a developer, I want...
        - This would help me...
        - The target audience is...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here.
      placeholder: |
        - This could be implemented by...
        - The API might look like...
        - Example code:
        ```python
        # Your example here
        ```
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (Minor change, few lines of code)
        - Medium (Moderate change, new functionality)
        - High (Major change, significant new feature)
        - Very High (Breaking change, architectural shift)
        - Not sure
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (Nice to have)
        - Medium (Would be helpful)
        - High (Important for my use case)
        - Critical (Blocking my work)
    validations:
      required: true

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes to existing APIs
        - label: This feature is backward compatible
        - label: I'm not sure about compatibility impact

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work or similar implementations.
      placeholder: |
        Similar to how Django does X...
        FastAPI implements this as...

        Example usage:
        ```python
        from nexus import feature

        # How it would work
        result = feature.do_something()
        ```
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: "Links to relevant documentation, similar features in other projects, etc."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
